using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Reflection;
using System.Reflection.Emit;
using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;
using Microsoft.Win32;
using SharpSvn.MSBuild.FileParsers;

namespace SharpSvn.MSBuild
{
    public enum Language
    {
        Unknown,
        cpp,
        csharp,
        vb
    }

    public class TransformAssemblyInfo : ITask
    {
        readonly List<string> _filesWritten = new List<string>();
        Language _language;

        public Microsoft.Build.Framework.IBuildEngine BuildEngine
        {
            get;
            set;
        }

        [Required]
        public string Language
        {
            get { return _language.ToString(); }
            set { _language = (Language)Enum.Parse(typeof(Language), value, true); }
        }

        [Required]
        public ITaskItem[] Sources
        {
            get;
            set;
        }

        public string SetVersion
        { get; set; }
        public string SetFileVersion
        { get; set; }
        public string SetInformationalVersion
        { get; set; }

        public string SetCopyright
        { get; set; }
        public string SetCompany
        { get; set; }
        public string SetTrademark
        { get; set; }
        public string SetConfiguration
        { get; set; }
        public string SetProduct
        { get; set; }
        public string SetTitle
        { get; set; }

        [Output]
        public ITaskItem[] FilesWritten
        {
            get
            {
                ITaskItem[] items = new ITaskItem[_filesWritten.Count];
                int n = 0;
                foreach (string f in _filesWritten)
                {
                    items[n++] = new TaskItem(f);
                }
                return items;
            }
        }

        public Microsoft.Build.Framework.ITaskHost HostObject
        {
            get;
            set;
        }

        public bool Execute()
        {
            foreach (ITaskItem ti in Sources)
            {
                string src = ti.GetMetadata("InfoSource");

                if (!File.Exists(src))
                    continue;

                string dest = ti.ItemSpec;
                string dir = Path.GetDirectoryName(dest);

                Directory.CreateDirectory(dir);

                _filesWritten.Add(dest);

                string tmp = dest + ".new";
                using (StreamWriter sw = File.CreateText(tmp))
                using (StreamReader sr = File.OpenText(src))
                {
                    string line;

                    LanguageParser parser = CreateParser();

                    if (!string.IsNullOrWhiteSpace(SetVersion))
                        parser.AddAttribute(typeof(AssemblyVersionAttribute));
                    if (!string.IsNullOrWhiteSpace(SetVersion) || !string.IsNullOrWhiteSpace(SetFileVersion))
                        parser.AddAttribute(typeof(AssemblyFileVersionAttribute));
                    if (!string.IsNullOrWhiteSpace(SetVersion) || !string.IsNullOrWhiteSpace(SetInformationalVersion))
                        parser.AddAttribute(typeof(AssemblyInformationalVersionAttribute));
                    if (!string.IsNullOrWhiteSpace(SetCopyright))
                        parser.AddAttribute(typeof(AssemblyCopyrightAttribute));
                    if (!string.IsNullOrWhiteSpace(SetCompany))
                        parser.AddAttribute(typeof(AssemblyCompanyAttribute));
                    if (!string.IsNullOrWhiteSpace(SetTrademark))
                        parser.AddAttribute(typeof(AssemblyTrademarkAttribute));
                    if (!string.IsNullOrWhiteSpace(SetConfiguration))
                        parser.AddAttribute(typeof(AssemblyConfigurationAttribute));
                    if (!string.IsNullOrWhiteSpace(SetProduct))
                        parser.AddAttribute(typeof(AssemblyProductAttribute));
                    if (!string.IsNullOrWhiteSpace(SetTitle))
                        parser.AddAttribute(typeof(AssemblyTitleAttribute));


                    parser.WriteComment(sw, string.Format("Generated by {0}", typeof(TransformAssemblyInfo).Assembly.FullName));
                    parser.WriteComment(sw, string.Format("Based on {0}", src));

                    while (null != (line = sr.ReadLine()))
                    {
                        if (parser.FilterLine(line))
                            parser.WriteComment(sw, line);
                        else
                            sw.WriteLine(line);
                    }

                    sw.WriteLine();
                    sw.WriteLine();
                    parser.WriteComment(sw, "** Generated attributes **");

                    if (!string.IsNullOrWhiteSpace(SetVersion))
                        parser.WriteAttribute(sw, typeof(AssemblyVersionAttribute), SetVersion);
                    if (!string.IsNullOrWhiteSpace(SetFileVersion))
                        parser.WriteAttribute(sw, typeof(AssemblyVersionAttribute), SetFileVersion);
                    if (!string.IsNullOrWhiteSpace(SetInformationalVersion))
                        parser.WriteAttribute(sw, typeof(AssemblyVersionAttribute), SetFileVersion);
                    if (!string.IsNullOrWhiteSpace(SetCopyright))
                        parser.WriteAttribute(sw, typeof(AssemblyCopyrightAttribute), SetCopyright);
                    if (!string.IsNullOrWhiteSpace(SetCompany))
                        parser.WriteAttribute(sw, typeof(AssemblyCompanyAttribute), SetCompany);
                    if (!string.IsNullOrWhiteSpace(SetTrademark))
                        parser.WriteAttribute(sw, typeof(AssemblyTrademarkAttribute), SetTrademark);
                    if (!string.IsNullOrWhiteSpace(SetConfiguration))
                        parser.WriteAttribute(sw, typeof(AssemblyConfigurationAttribute), SetConfiguration);
                    if (!string.IsNullOrWhiteSpace(SetProduct))
                        parser.WriteAttribute(sw, typeof(AssemblyProductAttribute), SetProduct);
                    if (!string.IsNullOrWhiteSpace(SetTitle))
                        parser.WriteAttribute(sw, typeof(AssemblyTitleAttribute), SetTitle);
                }

                // TODO: Compare tmp with dest and only copy when changed
                File.Copy(tmp, dest, true);
            }
            return true;
        }

        private LanguageParser CreateParser()
        {
            switch (_language)
            {
                case MSBuild.Language.cpp:
                    return new CppParser();
                case MSBuild.Language.csharp:
                    return new CSharpParser();
                case MSBuild.Language.vb:
                    return new VBParser();
                default:
                    throw new NotImplementedException("Unimplemented language");
            }
        }
    }
}
