//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpSvn.UI {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpSvn.UI.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A client certificate is required for accessing server {0} at {1}..
        /// </summary>
        internal static string ACertificateFileIsRequiredForAccessingServerXatY {
            get {
                return ResourceManager.GetString("ACertificateFileIsRequiredForAccessingServerXatY", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connect to Subversion.
        /// </summary>
        internal static string ConnectToSubversion {
            get {
                return ResourceManager.GetString("ConnectToSubversion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The certificate for server {0} at {1} requires a passphrase..
        /// </summary>
        internal static string ThePassPhraseForTheClientCertificateForXIsRequired {
            get {
                return ResourceManager.GetString("ThePassPhraseForTheClientCertificateForXIsRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The server {0} at {1} requires a username..
        /// </summary>
        internal static string TheServerXatYRequiresAUsername {
            get {
                return ResourceManager.GetString("TheServerXatYRequiresAUsername", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The server {0} at {1} requires a username and password..
        /// </summary>
        internal static string TheServerXatYRequiresAUsernameAndPassword {
            get {
                return ResourceManager.GetString("TheServerXatYRequiresAUsernameAndPassword", resourceCulture);
            }
        }
    }
}
